// Библиотека сгенерированных звуков. Поиск, фильтр по категории, drag → таймлайн.

import { useEffect, useState } from "react";
import { api, audioUrl } from "@/lib/api";
import type { SoundMetadata } from "@/types";
import { useAudioEngine } from "@/hooks/useAudioEngine";
import { useUIStore } from "@/store/uiStore";

export function SoundBrowser(): JSX.Element {
  const [items, setItems] = useState<SoundMetadata[]>([]);
  const [total, setTotal] = useState(0);
  const [q, setQ] = useState("");
  const [category, setCategory] = useState<string | null>(null);
  const [favorites, setFavorites] = useState(false);
  const [loading, setLoading] = useState(false);
  const { engine } = useAudioEngine();
  const libraryRevision = useUIStore((s) => s.libraryRevision);
  const previewPlayingUrl = useUIStore((s) => s.previewPlayingUrl);

  const load = async (): Promise<void> => {
    setLoading(true);
    try {
      const res = await api.library({
        q: q || undefined,
        category: category ?? undefined,
        favorite: favorites || undefined,
        limit: 60,
      });
      setItems(res.items);
      setTotal(res.total);
    } catch {
      setItems([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const id = setTimeout(load, 200);
    return () => clearTimeout(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [q, category, favorites, libraryRevision]);

  const categories = Array.from(new Set(items.map((i) => i.category).filter(Boolean) as string[]));

  const onDragStart = (e: React.DragEvent, s: SoundMetadata): void => {
    e.dataTransfer.setData("application/sfx-clip", JSON.stringify({
      url: audioUrl(s.url),
      filename: s.filename,
      duration: s.duration,
      sample_rate: s.sample_rate,
      label: `${s.prompt.slice(0, 20)}#${s.seed}`,
    }));
    e.dataTransfer.effectAllowed = "copy";
  };

  return (
    <div>
      <div className="row" style={{ gap: 8 }}>
        <div className="label">Library</div>
        <span className="label" style={{ color: "var(--fg-3)" }}>
          {loading ? "…" : `${items.length} / ${total}`}
        </span>
        <div className="spacer" />
        <input
          placeholder="search prompts / tags…"
          value={q} onChange={(e) => setQ(e.target.value)}
          style={{ width: 220 }}
        />
        <button className={favorites ? "primary" : ""} onClick={() => setFavorites(!favorites)}>
          ★ Fav
        </button>
        <button className="ghost" onClick={load}>↻</button>
      </div>

      <div className="tag-row" style={{ marginTop: 6 }}>
        <button
          className={`chip ${category === null ? "active" : ""}`}
          onClick={() => setCategory(null)}
        >all</button>
        {categories.map((c) => (
          <button key={c} className={`chip ${category === c ? "active" : ""}`}
            onClick={() => setCategory(c)}>{c}</button>
        ))}
      </div>

      <div className="lib-grid">
        {items.map((s) => {
          const itemUrl = audioUrl(s.url);
          const isPlaying = previewPlayingUrl === itemUrl;
          return (
          <div
            key={s.id}
            className="lib-card"
            draggable
            onDragStart={(e) => onDragStart(e, s)}
            title={s.prompt}
          >
            <div className="row" style={{ gap: 4 }}>
              <button
                className="ghost icon"
                style={{ width: 22, height: 22, padding: 0 }}
                onClick={() => isPlaying ? engine.stopPreview() : engine.previewOnce(itemUrl)}
                title={isPlaying ? "Stop preview" : "Play preview"}
              >{isPlaying ? "⏸" : "▶"}</button>
              <button
                className={`ghost icon ${s.favorite ? "primary" : ""}`}
                style={{ width: 22, height: 22, padding: 0, fontSize: 11 }}
                onClick={async () => {
                  await api.setFavorite(s.id, !s.favorite);
                  load();
                }}
              >★</button>
              <span className="mono" style={{ color: "var(--fg-3)", fontSize: 10 }}>
                {s.duration.toFixed(2)}s
              </span>
            </div>
            <div style={{ marginTop: 4, color: "var(--fg-1)" }}>
              {s.prompt.length > 50 ? s.prompt.slice(0, 50) + "…" : s.prompt}
            </div>
            <div className="tag-row" style={{ marginTop: 4 }}>
              {s.model && (
                <span
                  className="chip"
                  style={{ fontSize: 9, padding: "1px 6px", background: "var(--bg-3)", color: "var(--accent-2)" }}
                  title={`Generated by ${s.model}`}
                >
                  {s.model.replace(/-/g, " ").replace("stable audio open", "SAO").replace("tangoflux", "TF")}
                </span>
              )}
              {s.category && <span className="chip" style={{ fontSize: 9, padding: "1px 6px" }}>{s.category}</span>}
              {s.tags.slice(0, 2).map((t) => (
                <span key={t} className="chip" style={{ fontSize: 9, padding: "1px 6px" }}>{t}</span>
              ))}
            </div>
          </div>
          );
        })}
        {!loading && items.length === 0 && (
          <div style={{ color: "var(--fg-3)", padding: 16, gridColumn: "1 / -1", textAlign: "center" }}>
            No sounds yet — generate something on the right.
          </div>
        )}
      </div>
    </div>
  );
}
